name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Deploy to AWS EC2
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
          USER: ${{ secrets.EC2_USERNAME }}
          HOST: ${{ secrets.EC2_HOST }}
        run: |
          echo "$SSH_KEY" > ssh_key.pem
          chmod 600 ssh_key.pem
          ssh -o StrictHostKeyChecking=no -i ssh_key.pem $USER@$HOST << 'EOF'
            cd /home/ubuntu/InvestmentAnalysis
            git pull origin main
            source venv/bin/activate || python3.9 -m venv venv && source venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt
            sudo systemctl restart my_app
            sudo systemctl restart data_access
          EOF
          rm ssh_key.pem
